# Generated by Django 3.2.25 on 2024-06-26 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=256)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^\\+91\\d{10}$')])),
            ],
        ),
    ]
