# Generated by Django 5.0.7 on 2024-07-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0004_alter_recruitmentmaster_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentmaster',
            name='profile_source',
            field=models.CharField(default='Direct', max_length=256),
        ),
    ]
