# Generated by Django 5.0.7 on 2024-07-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0005_recruitmentmaster_profile_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentmaster',
            name='profile_source',
            field=models.CharField(max_length=256),
        ),
    ]
