# Generated by Django 5.0.7 on 2024-07-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0006_alter_recruitmentmaster_profile_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentmaster',
            name='experience',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
