# Generated by Django 5.0.7 on 2024-07-27 17:55

import STAS.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0008_alter_recruitmentmaster_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentmaster',
            name='mobile_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13), STAS.models.valid_phone_number_check]),
        ),
    ]
