# Generated by Django 5.0.7 on 2024-07-28 12:37

import STAS.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0009_alter_recruitmentmaster_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentmaster',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='recruitmentmaster',
            name='mobile_number',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13), STAS.models.valid_phone_number_check]),
        ),
        migrations.AlterField(
            model_name='recruitmentmaster',
            name='profile_source',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
