# Generated by Django 5.0.7 on 2024-07-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0010_recruitmentmaster_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentmaster',
            name='id',
        ),
        migrations.AlterField(
            model_name='recruitmentmaster',
            name='slug',
            field=models.SlugField(default='', primary_key=True, serialize=False),
        ),
    ]
