# Generated by Django 5.0.7 on 2024-08-07 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=256)),
                ('vendor_email1', models.CharField(max_length=256)),
                ('vendor_email2', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='recruitmentmaster',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='recruitmentmaster',
            name='vendor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='STAS.vendorname'),
        ),
    ]
