# Generated by Django 3.2.25 on 2024-06-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0002_recruitmentmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='email',
            field=models.CharField(default='test@Example.com', max_length=100),
        ),
    ]
