# Generated by Django 5.0.7 on 2024-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0003_alter_vendorname_vendor_email2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorname',
            name='vendor_email1',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
