# Generated by Django 5.0.7 on 2024-08-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0004_alter_vendorname_vendor_email1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentmaster',
            name='vendor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate', to='STAS.vendorname'),
        ),
    ]
