# Generated by Django 5.0.7 on 2024-10-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAS', '0005_alter_recruitmentmaster_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
